services:
  ironbucket:
    build: .
    image: ironbucket:latest
    ports:
      - "172.17.0.1:20000:9000"
    volumes:
      - ./s3:/s3
      - ./.env:/app/.env
    environment:
      - RUST_LOG=ironbucket=info,tower_http=info
      - STORAGE_PATH=/s3
    restart: always
